# Generated by Django 5.2.2 on 2025-08-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_guest',
        ),
    ]
