# Generated by Django 5.2.2 on 2025-08-26 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid UK 11-digit number or an international number starting with +', regex='(^0\\d{10}$)|(^\\+?\\d{7,15}$)')]),
        ),
    ]
